[package]
name = "jsonist"
version = "0.0.1"
authors = ["Peter Heesterman <heesterman.peter@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
